server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/sk_anruo/microservicecloud-config.git
          #uri: git@gitee.com:sk_anruo/microservicecloud-config.git
          username: ***
          password: ***