server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
    
zuul: 
  prefix: /sk # 指定前缀
  ignored-services: "*" # 指定忽略的服务名，*匹配所有
  routes: 
    mydept.serviceId: microservicecloud-dept # 设置对服务名的路径映射
    mydept.path: /mydept/**
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
info:
  app.name: sk-microcloud
  company.name: www.sk.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

